urls = [
    "https://www.bbc.co.uk/iplayer/episode/m002hdd8/the-silence-of-the-lambs"
]

[folders]
download_dir = "./download" # where files will be downloaded to
media_dir = "../media"       # where files will be written to after transcode
transcode_dir = "./transcode" # where temp transcode files will be

[pipeline]
transcode = true  # whether to transcode the downloaded files
delete_downloads = true #whether to delete full downloads

[download_settings]
allsubtitles = true
writesubtitles = true
quiet = true
noprogress = false
outtmpl = "%(title)s.%(ext)s"
ratelimit = 1_000_000

[transcode_settings]
encoder = "qsv" # one of qsv, vaapi, none
quality = 20
device = "/dev/dri/renderD128"
crop = true # whether to remove padding

[permission_settings]
enable = true #whether to enable changing of user, group, permissions
file_perms = 664
dir_perms = 775
owner = "sam"
group = "media"

[title_overrides]
# put iplayer title and title for tmdb
"Doctor Who (2005–2022), Series 9, New Series Prologue" = "Doctor Who (2005–2022), Season 9 Prologue"
"Doctor Who (2005–2022), Mini Episode - The Night of the Doctor" = "Doctor Who (2005–2022), The Night of the Doctor"
"Doctor Who (2005–2022), The Doctor, the Widow and the Wardrobe" = "Doctor Who (2005–2022), , The Doctor, the Widow and the Wardrobe"
"Doctor Who (2005–2022), Series 2, Love and Monsters" = "Doctor Who (2005–2022), Series 2, Love & Monsters"
"Peaky Blinders, Series 5, Mr Jones" = "Peaky Blinders, Series 5, Mr. Jones"
"Suits, Series 7, Goodbye" = "Suits, Series 7, Good-bye"
"Suits, Series 5, Self Defence" = "Suits, Series 5, Self Defense"
"Suits, Series 2, Zane vs Zane" = "Suits, Series 2, Zane vs. Zane"
"Suits, Series 1, The Shelf Life" = "Suits, Series 1, Shelf Life"
"Trying, Series 2, Maddest, Sweetest Thing" = "Trying, Series 2, Maddest Sweetest Thing"
