urls = [
    "https://www.bbc.co.uk/iplayer/episode/b007q86z/the-jackal",
    "https://www.bbc.co.uk/iplayer/episode/m002t67f/la-chimera",
    "https://www.bbc.co.uk/iplayer/episode/m0029l6s/letter-to-brezhnev",
    "https://www.bbc.co.uk/iplayer/episode/m002273h/the-mask",
    "https://www.bbc.co.uk/iplayer/episode/b00z0f1d/the-prestige",
    "https://www.bbc.co.uk/iplayer/episode/b06vyf02/brooklyn",
"https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who-20052022",
"https://www.bbc.co.uk/iplayer/episodes/b045fz8r/peaky-blinders",
]

[folders]
download_dir = "./download" # where files will be downloaded to
media_dir = "../media"       # where files will be written to after transcode
transcode_dir = "./transcode" # where temp transcode files will be

[pipeline]
transcode = true  # whether to transcode the downloaded files
delete_downloads = true #whether to delete full downloads

[download_settings]
allsubtitles = true
writesubtitles = true
quiet = true
noprogress = false
outtmpl = "%(title)s.%(ext)s"
ratelimit = 1_000_000

[transcode_settings]
encoder = "qsv" # one of qsv, vaapi, none
quality = 20
device = "/dev/dri/renderD128"
crop = true # whether to remove padding

[permission_settings]
enable = true #whether to enable changing of user, group, permissions
file_perms = 664
dir_perms = 775
owner = "sam"
group = "media"
