urls = [
"https://www.bbc.co.uk/iplayer/episode/m001tfnl/doctor-who-christmas-special-the-church-on-ruby-road",
"https://www.bbc.co.uk/iplayer/episode/m002c5lx/doctor-who-season-2-5-the-story-and-the-engine?seriesId=p0gglvqn-structural-3-m0029db6",
"https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who-20052022?seriesId=b006q2x0-structural-4-b009wxzy",
"https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who-20052022?seriesId=b006q2x0-structural-3-b006v193",
"https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who-20052022?seriesId=b006q2x0-structural-2-b006v18m",
"https://www.bbc.co.uk/iplayer/episodes/b006q2x0/doctor-who-20052022?seriesId=b006q2x0-structural-1-b007vvcq"
]

[folders]
download_dir = "./download" # where files will be downloaded to
media_dir = "u410:/var/lib/drive/media"       # where files will be written to after transcode
transcode_dir = "./transcode" # where temp transcode files will be

[pipeline]
transcode = true  # whether to transcode the downloaded files
delete_downloads = true #whether to delete full downloads
max_non_transcoded = 5 # max full-quality downloads waiting for transcode/move at once

[download_settings]
format =  "bv*+ba[language=en]/bv*+ba/best"
subtitleslangs = ["en.*"]
writesubtitles = true
quiet = true
noprogress = false
#ratelimit = 1_000_000

[transcode_settings]
encoder = "none" # one of qsv, vaapi, none
quality = 20
device = "/dev/dri/renderD128"
crop = true # whether to remove padding

[permission_settings]
enable = true #whether to enable changing of user, group, permissions
file_perms = 664
dir_perms = 775
owner = "sam"
group = "media"

[title_overrides]
# put iplayer title and title for tmdb
"Doctor Who, Christmas Special： The Church on Ruby Road" = "Doctor Who, Specials, The Church on Ruby Road"
"Doctor Who, Season 2, The Story and the Engine" = "Doctor Who, Season 2, The Story & the Engine"
"Doctor Who (2005–2022), Series 12, Spyfall, Part 2" = "Doctor Who (2005–2022), Series 12, Spyfall (2)"
"Doctor Who (2005–2022), Series 12, Spyfall, Part 1" = "Doctor Who (2005–2022), Series 12, Spyfall (1)"
"Doctor Who (2005–2022), Series 9, New Series Prologue" = "Doctor Who (2005–2022), Season 9 Prologue"
"Doctor Who (2005–2022), Mini Episode - The Night of the Doctor" = "Doctor Who (2005–2022), The Night of the Doctor"
"Doctor Who (2005–2022), The Doctor, the Widow and the Wardrobe" = "Doctor Who (2005–2022), , The Doctor, the Widow and the Wardrobe"
"Doctor Who (2005–2022), Series 2, Love and Monsters" = "Doctor Who (2005–2022), Series 2, Love & Monsters"
"Peaky Blinders, Series 5, Mr Jones" = "Peaky Blinders, Series 5, Mr. Jones"
"Suits, Series 7, Goodbye" = "Suits, Series 7, Good-bye"
"Suits, Series 5, Self Defence" = "Suits, Series 5, Self Defense"
"Suits, Series 2, Zane vs Zane" = "Suits, Series 2, Zane vs. Zane"
"Suits, Series 1, The Shelf Life" = "Suits, Series 1, Shelf Life"
"Trying, Series 2, Maddest, Sweetest Thing" = "Trying, Series 2, Maddest Sweetest Thing"
